app/urls.py
from os import name
from django.urls import path
from .views import createtest, adminDashboard, log_in, log_out, index, subject, \
    test, register, users, start_single_test, result, delete_user, start, score, subject_categories, comment, \
    view_categories, add_file, url_test, userpage, allusers, changestatus, chat, edit_test, delete_test, \
    start_multiple_test, delete_attempt

urlpatterns = [
    path('', index, name='index'),
    path('register/' , register, name='register'),
    path('login/', log_in, name='log_in'),
    path('log_out/' , log_out , name='log_out'),

    path('add_file/',add_file,name='add_file'),
    path('dashboard/',adminDashboard,name='dashboard'),
    path('subject/',subject,name='subject'),
    path('subject_categories/<int:id>/',subject_categories,name='subject_categories'),
    path('users/',users, name='users'),
    path('delete_user/<int:id>/',delete_user, name='delete_user'),
    path('delete_test/<int:id>/',delete_test, name='delete_test'),
    path('delete_attempt/<int:id>/',delete_attempt, name='delete_attempt'),

    path('check/',test,name='check'),

    path('test/<int:id>/',start_single_test,name='test'),
    path('startattempt/',start_multiple_test,name='multipletest'),
    path('result/',result,name='result'),
    path('scores/<int:id>/',score,name='score'),
    path('start/',start,name='start'),
    path('comment/<int:id>/',comment,name='comment'),


    path('categories/<int:id>', view_categories, name='subjects'),
    path('edit_test/<int:id>', edit_test, name='edit_test'),
    path('categories/<int:id>/', view_categories, name='subjects'),
    path('url_test/', url_test, name='url_test'),
    path('allusers/', allusers, name='allusers'),

    path('userpage/<int:id>/', userpage, name='userpage'),
    path('changestatus/', changestatus, name='changestatus'),
    path('chat/<int:id>', chat, name= 'chat')
]

onlinetest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Visitors(models.Model):
    visitor = models.CharField(max_length=20,null=True)
    visited = models.PositiveIntegerField(default=0)
    data = models.DateTimeField(auto_now_add=True)
    @property
    def addvisitor(self):
        self.visited += 1
        self.save()

class Profile(models.Model):
    USER_TYPE = (
        ('Talaba','Talaba'),
        ('Abiturient','Abiturient'),
        ("O'qituvchi","O'qituvchi")
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    status = models.BooleanField(default=True)
    image = models.ImageField(upload_to = 'user_images', blank=True, null = True)
    user_type = models.CharField(max_length=10 , choices=USER_TYPE , default='Unset')
    city = models.CharField(max_length=20,null=True , blank=True)

    @property
    def imageURL(self):
        try:
            return self.image.url
        except:
            return ''
    
    def __str__(self):
        return self.user.username


class Subject(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='subject_images', null=True, blank=True)
    description = models.TextField(null=True)

    @property
    def imageURL(self):
        try:
            return self.image.url
        except:
            return ''

    def __str__(self):
        return self.name + " " + str(self.id)


class Subject_categories(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField(null=True)

    @property
    def imageURL(self):
        try:
            return self.image.url
        except:
            return ''

    def __str__(self):
        return self.name + " " + str(self.id)


class Question(models.Model):
    subject = models.ForeignKey(Subject_categories, on_delete=models.SET_NULL, null=True)
    question = RichTextUploadingField(blank=True, null=True)
    var1 = RichTextUploadingField(blank=True, null=True)
    var2 = RichTextUploadingField(blank=True, null=True)
    var3 = RichTextUploadingField(blank=True, null=True)
    var4 = RichTextUploadingField(blank=True, null=True)
    ans = RichTextUploadingField(blank=True, null=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id}-test {self.subject.name}"

class Attempt(models.Model):
    status = models.BooleanField(default=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    started_time = models.DateTimeField(auto_now_add=True)


class Test(models.Model):
    block = models.ForeignKey(Attempt, on_delete=models.CASCADE)
    subject_category = models.ForeignKey(Subject_categories, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True)
    
    def __str__(self):
        return self.subject_category.name


class Test_files(models.Model):
    subject = models.ForeignKey(Subject_categories, on_delete=models.CASCADE, null=True)
    test_file = models.FileField(upload_to='test_files')

    @property
    def fileURL(self):
        try:
            return self.test_file.url
        except:
            return ''


class Answers(models.Model):
    attempt = models.ForeignKey(Test, on_delete=models.CASCADE, null=True, related_name='test_subject')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    user_asnwer = models.CharField(max_length=200, null=True)
    correct = models.BooleanField(default=False)

    def __srt__(self):
        return self.test.subject_category.name


class Comment(models.Model):
    subject = models.ForeignKey(Subject_categories, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comment = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + ' ' + self.comment[0:10]

    @property
    def time(self):
        return self.created_at.strftime('%d-%M-%Y')

app/templates/app/Add_category.html
{% extends 'app/main.html' %}
{% block content %}
    {% load static %}
    <!-- section -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-10 layout_padding_2" style="margin: 0 auto; text-align: center;">
                    <div class="full">
                        <img style="filter: blur(3px); width: 400px;" src="{{ image }}" alt="#"/>
                    </div>
                </div>
                <div class="col-md-8 layout_padding_2" style="margin: -150px auto 0 auto;">
                    <div class="full">
                        <div class="heading_main text_align_center">
                            <h2><span>Welcome To</span> {{ subject_name }}</h2>
                        </div>
                        <div class="full">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.
                                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                                commodo consequat.
                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                nulla pariatur.
                                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                                mollit anim id est laborum</p>
                        </div>
                    </div>
                </div>

            </div>
            {% for subject in subjects %}
                <div class="row">
                    <div class="col-md-6 layout_padding_2">
                        <div class="full">
                            <div class="heading_main text_align_left">
                                <h2><span>{{ subject.name }}</span></h2>
                            </div>
                            <div class="full">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua.
                                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                                    ex ea commodo consequat.
                                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                                    fugiat nulla pariatur.
                                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                                    mollit anim id est laborum</p>
                            </div>
                        </div>
                        <button class="btn btn-success"><a href="{% url 'test' subject.id %}">Start test</a></button>
                    </div>
                    <div class="col-md-6 layout_padding_2">
                        <div class="full">
                            <img src="{{ subject.imageURL }}" style="width: 400px; margin-left: 50px;" alt="#"/>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- end section -->
{% endblock %}

app/templates/app/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
</head>
<body>

<div class="col-md-10 comment">
    <div class="full">
        {% if comment %}
            {% for comment in comment %}
                <small>{{ comment.user.username }}</small><br>
                <b>{{ comment.comment|safe }}</b><br>
                <small>{{ comment.time }}</small><br>
                <hr>
            {% endfor %}
        {% else %}
            <p>No comments so far...</p>
        {% endif %}
    </div>
</div>
<div>
    <form action="{% url 'comment' id %}" method="post"
          style="width: 100%; margin-top: 10px; text-align: center;">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success">Send</button>
    </form>
</div>

</body>
</html>

app/templates/app/index.html
{% extends 'app/main.html' %}
{% block content %}
{% load static %}

    <!-- slider start -->
    <div id="carouselExampleCaptions" class="carousel slide top_slider" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img height="550px" src="{% static 'images/slider_1.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img height="550px" src="{% static 'images/slider_2.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Second slide label</h5>
              <p>Some representative placeholder content for the second slide.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img height="550px" src="{% static 'images/slider_3.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Third slide label</h5>
              <p>Some representative placeholder content for the third slide.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <!-- slider end -->

    <!-- Tabbar menu start -->
    <div class="tabbar_menu">
        <ul>
            <li><i class="fas fa-university "></i><br>University Life</li>
            <li><i class="fas fa-graduation-cap"></i><br>Graduation</li>
            <li><i class="fas fa-running "></i><br>Athletics</li>
            <li><i class="fas fa-share-alt"></i><br>Social</li>
            <li><i class="fas fa-map-marker-alt "></i><br>Location</li>
            <li><i class="fas fa-phone-volume"></i><br>Call us</li>
            <li><i class="fas fa-at "></i><br>Email</li>
        </ul>
    </div>
    <!-- Tabbar menu end -->

    <!-- content start -->
    <div class="content">
        <div class="left_content">
            <h1><span>Welcome To</span> Education</h1>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores assumenda blanditiis corrupti itaque quod reprehenderit expedita officiis nesciunt veritatis provident fugit accusantium minus, dolorem ratione ea, quasi, velit aliquid deserunt impedit magni nostrum quaerat repellat cumque. Modi unde officiis voluptates?</p>
        </div>
        <div class="rihgt_content">
            <img width="100%" src="{% static 'images/right_content.png' %}" alt="">
        </div>
    </div>
    <!-- content end -->
    	<!-- section -->
        <div class="section layout_padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="full">
                            <div class="heading_main" style="text-align: center; margin: 35px 0;">
                               <h2><span>Popular </span>Courses</h2>
                            </div>
                          </div>
                    </div>
                    {% for subject in subjects %}
                    <div class="col-md-3">
                        <div class="full blog_img_popular" style="text-align: center;">
                           <img class="img-responsive" src="{{ subject.imageURL }}" alt="#" />
                           <h4><a style="text-decoration: none;" href="{% url 'subjects' subject.id %}">{{ subject.name }}</a></h4>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- end section -->
    
        <!-- section -->
        <div class="section layout_padding padding_bottom-0">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="full">
                            <div class="heading_main" style="text-align: center; margin: 35px 0;">
                               <h2><span>Derictions / Yo'nalishlar</span></h2>
                            </div>
                          </div>
                    </div>
                  </div>
                   <div class="row" style="margin-bottom: 50px;">
                    <div class="col-lg-12">
                        <div id="demo" class="carousel slide" data-ride="carousel">
    
                            <!-- The slideshow -->
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="row">
                                        {% for subject in subjects %}
                                        <div class="col-lg-3 col-md-3 col-sm-4">
                                           <div class="full blog_img_popular" style="text-align: center;">
                                              <img class="img-responsive" src="{{ subject.imageURL }}" />
                                              <h4>{{ subject.name }}</h4>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
    
                </div>
               </div>
            </div>
        <!-- end section -->


{% endblock %}

app/templates/app/login.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <h6 class="mb-4 text-muted">Login to your account</h6>
                    <form action="" method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                            <label for="text" class="form-label">User name</label>
                            <input type="text" class="form-control" placeholder="username" name="username" required>
                        </div>
                        <div class="mb-3 text-start">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                        </div>
                        <div class="mb-3 text-start">
                            <div class="form-check">
                              <input class="form-check-input" name="remember" type="checkbox" value="" id="check1">
                              <label class="form-check-label" for="check1">
                                Remember me on this device
                              </label>
                            </div>
                        </div>
                        <button class="btn btn-primary shadow-2 mb-4">Login</button>
                    </form>
                    <p class="mb-2 text-muted">Forgot password? <a href="#">Reset</a></p>
                    <p class="mb-0 text-muted">Don't have account yet? <a href="{% url 'register' %}">Signup</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

app/templates/app/subject_categories.html
{% extends 'app/dashboard.html' %}
{% block content %}
{% load static %}
<button type="button" class="btn btn-success" style="float: right; margin: 10px ;" data-bs-toggle="modal" data-bs-target="#AddCategoryModal"><i class="fa fa-folder"></i> Add category</button>
<button type="button" class="btn btn-success" style="float: right; margin: 10px 10px;" data-bs-toggle="modal" data-bs-target="#AddtestfileModal"><i class="fa fa-folder"></i> Add test files</button><br>
<div class="content" style="margin-top: 40px;">
    <div class="container">

        <!-- Modal -->
        <div class="modal fade" id="btnUpdate" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog modal-xl modal-dialog-scrollable">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
                <form style="overflow: scroll"  action="{% url 'url_test' %}" method="post">
                    {% csrf_token %}
                  <div  id="subject_test" class="modal-body">

                  </div>
                    <button type="submit" class="btn btn-primary">Understood</button>
                </form>
            </div>
          </div>
        </div>


        <div class="col-lg-6">
                <div class="card">
                    <div class="modal fade" id="AddCategoryModal" role="dialog" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title"><b>ADD SUBJECT CATEGORY</b></h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body text-start">
                                <form accept-charset="utf-8" method="post" enctype="multipart/form-data">
                                   {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="name" class="form-label">Name</label>
                                        <input type="text" name="name" placeholder="Please input a name" class="form-control">
                                    </div>
                                    <div class="mb-3">
                                        <label for="image" class="form-label">Upload image</label>
                                        <input type="file" name="image" placeholder="Please input subject name" class="form-control">
                                    </div>
                                    <div class="mb-3">
                                        <label for="description" class="form-label">Description</label>
                                        <input type="text" name="description" placeholder="Description..." class="form-control">
                                    </div>
                                    <div class="mb-3">
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                                    </div>
                                </form>
                              </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="AddtestfileModal" role="dialog" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title"><b>ADD SUBJECT CATEGORY</b></h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body text-start">
                                <form action="{% url 'add_file' %}" accept-charset="utf-8" method="post" enctype="multipart/form-data">
                                   {% csrf_token %}
                                   <div class="mb-3">
                                        <label class="form-label">Select Category</label>        
                                        <select name="test_file" class="form-control">
                                            {% for subjects in subject_categories %}
                                                <option value="{{ subjects.name }}">{{ subjects.name }}</option>
                                            {% endfor %}
                                        </select>
                                   </div>
                                    <div class="mb-3">
                                        <label class="form-label">Upload file</label>
                                        <input type="file" name="file" placeholder="Choose file" class="form-control">
                                    </div>
                                    <div class="mb-3">
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                                    </div>
                                </form>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
        {% csrf_token %}
            {% for subject in subject_categories %}
            <div class="col-sm-6 col-md-6 col-lg-3 mt-3" style="display: inline-block;">
                <div class="card" style="padding: 10px 0;">
                    <div class="content">
                        <p style="text-align: left;">Subject category name: <b>{{subject.name}}</b></p>
                    </div>
                    <div>
                        <img style="width: 99%; height: 300px;" src="{{ subject.imageURL }}" alt="image">
                    </div>
                    <div class="content">
                        <p>Number of qustions: {{ subject.question_set.all.count }}</p>
                    </div>
                    <div>
                        <button class="btn btn-outline-danger" type="button"><a href="{% url 'edit_test' subject.id %}">Update test</a></button>
{#                        <button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#btnUpdate" onclick="update_test({{ subject.id }})">Update test</button>#}
                        <button class="btn btn-outline-success"><i class="fa fa-plus"></i> Add test</button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/subjects.html
{% extends 'app/dashboard.html' %}

{% block content %}
<div class="content">
    <div class="container">
        <button type="button" class="btn btn-success" style="float: right" data-bs-toggle="modal" data-bs-target="#addtestModal">Add subject</button>
        <div class="col-lg-6">
            <div class="card">
                    <div class="modal fade" id="addtestModal" role="dialog" tabindex="-1">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title"><b>ADD SUBJECT</b></h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-start">
                            <form accept-charset="utf-8" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="name" class="form-label">Name</label>
                                    <input type="text" name="name" placeholder="Please input a name" class="form-control">
                                </div>
                                <div class="mb-3">
                                    <label for="image" class="form-label">Upload image</label>
                                    <input type="file" name="image" placeholder="Please input subject name" class="form-control">
                                </div>
                                <div class="mb-3">
                                    <label for="description" class="form-label">Description</label>
                                    <input type="text" name="description" placeholder="Description..." class="form-control">
                                </div>
                                <div class="mb-3">
                                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            {% for subject in subjects %}
            <div class="col-sm-6 col-md-6 col-lg-3 mt-3" style="display: inline-block;">
                <div class="card" style="padding: 10px 0;">
                    <div class="content">
                        <p style="text-align: left;">Subject name: <b>{{subject.name}}</b></p>
                    </div>
                    <div>
                        <img style="width: 99%; height: 300px;" src="{{ subject.imageURL  }}" alt="image">
                    </div>
                    <div class="content">
                        <p>Number of categories: {{ subject.subject_categories_set.all.count }}</p>
                    </div>
                    <div>
                        <button class="btn btn-success" style="margin-left: 50px;"><a href="{% url 'subject_categories' subject.id %}">View categories</a></button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}